Vagrant.configure("2") do |config|
    # Set the box to Ubuntu 18.04 LTS (Bionic)
    config.vm.box = "hashicorp/bionic64"
    
    config.vm.network "public_network", bridge: "MediaTek Wi-Fi 6 MT7921 Wireless LAN Card"

    # Configure VirtualBox specific settings
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024  # 1GB RAM
        vb.cpus = 2       # 2 CPUs
    end
    # Sync Folder form host folder to guest folder
    config.vm.synced_folder "./Scripts", "/opt/scripts"

    # Configure network settings
    config.vm.network "private_network", ip: "192.168.56.16"

    config.vm.provision "shell", inline: <<-SHELL
        yum install httpd wget unzip git -y
        systemctl start httpd
        systemctl enable httpd
    SHELL
end